# Generated by Django 2.0.1 on 2018-01-30 10:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Published'), ('C', 'Closed'), ('R', 'Really Closed')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ui_schema_json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('version', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted'), ('V', 'Verified'), ('I', 'Invalid')], default='D', max_length=1)),
                ('token', models.CharField(db_index=True, default='bicJbCwcYGH2GMowkfmG2LIwpOD8gnZDOI3BliZ3j5k', max_length=256)),
                ('submission_date', models.DateTimeField()),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FormInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_image', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('short_description', models.TextField()),
                ('category', models.TextField()),
                ('research_questions', models.TextField()),
                ('text', models.TextField()),
                ('methodology', models.TextField()),
                ('faq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to='')),
                ('url', models.TextField(max_length=1000)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Investigation')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Investigation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='form_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FormResponse'),
        ),
    ]
