# Generated by Django 2.0.1 on 2018-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Submitted'), ('V', 'Verified')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='token',
            field=models.CharField(db_index=True, default='T-eRO7yIgqACrM09tD4vwD-gFgaSgBbqp7iBUEbDwp0', max_length=256),
        ),
    ]
