# Generated by Django 2.0.1 on 2018-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminstance',
            name='email_template',
            field=models.TextField(default='Thank you for participating in a crowdnewsroom investigation!'),
        ),
    ]
