# Generated by Django 2.0.1 on 2018-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'permissions': (('view_investigation', 'View investigation'), ('manage_investigation', 'Manage investigation'))},
        ),
    ]
