# Generated by Django 2.0.1 on 2018-02-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('A', 'Archived')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Published'), ('C', 'Closed'), ('A', 'Archived')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='token',
            field=models.CharField(db_index=True, default='RAoGZKYpN_oMXXRKiqLd4e-tvhQSeVPuqG9npl0ng0Q', max_length=256),
        ),
    ]
