# Generated by Django 2.0.1 on 2018-03-26 13:52

from django.db import migrations
from slugify import slugify_de

def slugify(value):
    return slugify_de(value, to_lower=True)


def make_slugs(apps, schema_editor):
    Investigation = apps.get_model('forms.Investigation')
    Form = apps.get_model('forms.Form')
    for i in Investigation.objects.all():
        i.slug = slugify(i.name)
        i.save()
    for f in Form.objects.all():
        f.slug = slugify(f.name)
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20180326_1352'),
    ]

    operations = [
        migrations.RunPython(make_slugs)
    ]
