# Generated by Django 2.0.1 on 2018-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='email',
            field=models.EmailField(default='old@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
