# Generated by Django 2.0.1 on 2018-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180326_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
