# Generated by Django 2.0.1 on 2018-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_forminstance_redirect_url_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminstance',
            name='email_template_html',
            field=models.TextField(default='Thank you for participating in a crowdnewsroom investigation!'),
        ),
    ]
