# Generated by Django 2.0.1 on 2018-04-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180326_1356'),
        ('forms', '0004_forminstance_email_template_html'),
    ]

    operations = [
    ]
