# Generated by Django 2.0.1 on 2018-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formresponse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('V', 'Verified'), ('I', 'Invalid')], default='S', max_length=1),
        ),
        migrations.RunSQL("UPDATE forms_formresponse SET status = 'S' where status = 'D'", reverse_sql="")
    ]
