# Generated by Django 2.0.1 on 2018-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_merge_20180403_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='data_privacy_url',
            field=models.URLField(null=True),
        ),
    ]
