# Generated by Django 2.0.1 on 2018-04-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20180418_1504'),
        ('forms', '0007_tags'),
    ]

    operations = [
    ]
