# Generated by Django 2.0.1 on 2018-06-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20180523_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('E', 'Editor'), ('V', 'Viewer')], default='V', max_length=1),
        ),
    ]
