# Generated by Django 2.0.1 on 2018-06-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20180523_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
