# Generated by Django 2.0.1 on 2018-06-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20180606_1352'),
        ('forms', '0011_auto_20180605_1430'),
    ]

    operations = [
    ]
