# Generated by Django 2.0.1 on 2018-06-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20180607_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='form_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forms.FormResponse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
