# Generated by Django 2.0.1 on 2018-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20180607_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forms.Tag'),
        ),
    ]
