# Generated by Django 2.0.1 on 2018-06-25 12:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_auto_20180608_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminstance',
            name='priority_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
