# Generated by Django 2.0.1 on 2018-07-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_forminstance_priority_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'permissions': (('view_investigation', 'View investigation'), ('manage_investigation', 'Manage investigation'), ('master_investigation', 'Delete investigation and manage owners'))},
        ),
    ]
