# Generated by Django 2.0.1 on 2018-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_invitation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='data_privacy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='faq',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='methodology',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='research_questions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
