# Generated by Django 2.0.1 on 2018-07-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20180720_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
