# Generated by Django 2.0.1 on 2018-08-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_forminstancetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
