# Generated by Django 2.0.1 on 2018-10-10 08:22

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import forms.mixins
import re


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_remove_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), forms.mixins.validate_slug_stricter]),
        ),
        migrations.AlterField(
            model_name='forminstance',
            name='priority_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='forminstancetemplate',
            name='priority_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='forminstancetemplate',
            name='ui_schema_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), forms.mixins.validate_slug_stricter]),
        ),
    ]
