# Generated by Django 2.0.9 on 2018-11-29 14:32

from django.db import migrations
from ..models import Investigation, UserGroup


def create_auth_groups(apps, schema_editor):
    # UserGroup = apps.get_model('forms.usergroup')
    # Investigation = apps.get_model('forms.investigation')
    for i in Investigation.objects.all():
        UserGroup.create_all_for(i)


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_auto_20181129_1422'),
    ]

    operations = [
        migrations.RunPython(create_auth_groups)
    ]
