# Generated by Django 2.0.9 on 2019-06-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_create_new_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_simple',
            field=models.BooleanField(default=False),
        ),
    ]
