# Generated by Django 2.0.9 on 2019-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_form_is_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminstancetemplate',
            name='is_simple',
            field=models.BooleanField(default=False),
        ),
    ]
