# Generated by Django 2.0.9 on 2019-06-06 10:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_forminstancetemplate_is_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forminstance',
            name='ui_schema_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
