# Generated by Django 2.0.9 on 2019-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_auto_20190606_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('it', 'Italian')], default='de', max_length=2),
        ),
    ]
