# Generated by Django 3.0.2 on 2020-01-21 09:35

import django.core.validators
from django.db import migrations, models
import forms.mixins
import re


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_form_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'permissions': (('watch_investigation', 'Watch investigation'), ('manage_investigation', 'Manage investigation'), ('admin_investigation', 'Admin investigation'), ('master_investigation', 'Delete investigation and manage owners'))},
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), forms.mixins.validate_slug_stricter]),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), forms.mixins.validate_slug_stricter]),
        ),
    ]
