language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage codecov
script:
  - coverage run --source='.' manage.py test
after_script:
  - coverage report
  - codecov
services:
  - postgresql
addons:
  postgresql: "9.6"
